apiVersion: v1
kind: Service
metadata:
  name: prom-money-rs
  namespace: home-sensors
spec:
  type: LoadBalancer
  selector:
    app: prom-money-rs
  ports:
    - name: http
      protocol: TCP
      port: 9090
      targetPort: 9090
