apiVersion: v1
kind: Service
metadata:
  name: nest-sensor
  namespace: home-sensors
spec:
  type: LoadBalancer
  selector:
    app: nest-sensor
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
