apiVersion: apps/v1
kind: Deployment
metadata:
  name: mqtt-prometheus-exporter
  namespace: home-sensors
  labels:
    app: mqtt-prometheus-exporter
spec:
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: mqtt-prometheus-exporter
  template:
    metadata:
      labels:
        app: mqtt-prometheus-exporter
    spec:
      imagePullSecrets:
        - name: ghcr-kj800x
      containers:
        - name: mqtt-prometheus-exporter
          image: ghcr.io/kj800x/mqtt-prometheus:master
          command: ["/bin/sh", "-c", "node lib/index.js"]
          entrypoint: ["docker-entrypoint.sh"]
          env:
            - name: NODE_ENV
              value: "production"
          ports:
            - containerPort: 8080
              protocol: TCP
          workingDir: "/app"
