apiVersion: v1
kind: Service
metadata:
  name: mqtt-prometheus-exporter
  namespace: home-sensors
spec:
  type: LoadBalancer
  selector:
    app: mqtt-prometheus-exporter
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
