apiVersion: cicd.coolkev.com/v1
kind: DeployConfig
metadata:
  name: manual-deploy-config
  namespace: home-sensors
spec:
  resourceType: Deployment
  autodeploy: false
  repo:
    owner: kj800x
    repo: test-repo
    defaultBranch: master
  spec:
    replicas: 1
    revisionHistoryLimit: 1
    selector:
      matchLabels:
        app: manual-deploy-config
    template:
      metadata:
        labels:
          app: manual-deploy-config
      spec:
        restartPolicy: OnFailure
        imagePullSecrets:
          - name: ghcr-kj800x
        containers:
          - name: manual-deploy-config
            image: ghcr.io/kj800x/test-repo
            command: ["./rust-hello-world"]
            ports:
              - containerPort: 8080
                protocol: TCP
