apiVersion: apps/v1
kind: Deployment
metadata:
  name: miniflux
  namespace: miniflux
  labels:
    app: miniflux
spec:
  revisionHistoryLimit: 1
  replicas: 1
  selector:
    matchLabels:
      app: miniflux
  template:
    metadata:
      labels:
        app: miniflux
    spec:
      containers:
      - name: miniflux
        image: miniflux/miniflux:latest
        command: ["/usr/bin/miniflux"]
        env:
        - name: CREATE_ADMIN
          value: "1"
        - name: ADMIN_USERNAME
          value: "kevin"
        - name: ADMIN_PASSWORD
          valueFrom:
            secretKeyRef:
              name: miniflux-admin-secret
              key: ADMIN_PASSWORD
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: miniflux-admin-secret
              key: DATABASE_URL
        - name: RUN_MIGRATIONS
          value: "1"
        - name: LISTEN_ADDR
          value: "0.0.0.0:80"
        ports:
        - containerPort: 80
      securityContext:
        runAsUser: 65534  # nobody
