apiVersion: v1
kind: Service
metadata:
  name: miniflux
  namespace: miniflux
  annotations:
    external-dns.alpha.kubernetes.io/hostname: miniflux.home.coolkev.com
spec:
  type: LoadBalancer
  selector:
    app: miniflux
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
