apiVersion: apps/v1
kind: Deployment
metadata:
  name: life-logger
  namespace: life-logger
  labels:
    app: life-logger
spec:
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: life-logger
  template:
    metadata:
      labels:
        app: life-logger
    spec:
      imagePullSecrets:
        - name: ghcr-kj800x
      containers:
        - name: life-logger
          image: ghcr.io/kj800x/life-logger-2:commit-131fb8ac04ab15a4a9a1e3f68e0c876ab59611cb
          command: ["life-logger-2-rs"]
          env:
            - name: SERVER_HOST
              value: "0.0.0.0"
            - name: SERVER_PORT
              value: "8080"
            - name: DATABASE_PATH
              value: "/data/db.db"
          ports:
            - containerPort: 8080
              protocol: TCP
          volumeMounts:
            - name: data
              mountPath: /data
      volumes:
        - name: data
          nfs:
            server: 10.60.1.15
            path: /data/services/life-logger
