apiVersion: v1
kind: Service
metadata:
  name: life-logger
  namespace: life-logger
spec:
  type: ClusterIP
  selector:
    app: life-logger
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080
