apiVersion: cicd.coolkev.com/v1
kind: DeployConfig
metadata:
  name: heartbeat-rs
  namespace: heartbeat-rs
spec:
  resourceType: Deployment
  autodeploy: true
  repo:
    owner: kj800x
    repo: heartbeat-rs
    defaultBranch: master
  spec:
    revisionHistoryLimit: 1
    replicas: 1
    selector:
      matchLabels:
        app: heartbeat-rs
    template:
      metadata:
        labels:
          app: heartbeat-rs
      spec:
        imagePullSecrets:
          - name: ghcr-kj800x
        containers:
          - name: heartbeat-rs
            image: ghcr.io/kj800x/heartbeat-rs
            command: [ "heartbeat-rs" ]
            env:
              - name: HEARTBEAT_URL
                value: "http://apps.coolkev.com:3005/api/push/SdiBYdO0Lr?status=up&msg=OK&ping="
              - name: HEARTBEAT_SLEEP
                value: "5"
            workingDir: "/usr/src/heartbeat-rs"
            resources:
              requests:
                cpu: "50m"
                memory: "64Mi"
              limits:
                cpu: "250m"
                memory: "128Mi"
