apiVersion: v1
kind: Service
metadata:
  name: mosquitto
  namespace: mosquitto
  annotations:
    external-dns.alpha.kubernetes.io/hostname: mqtt.home.coolkev.com
spec:
  type: LoadBalancer
  selector:
    app: mosquitto
  ports:
    - name: mqtt
      protocol: TCP
      port: 1883
      targetPort: 1883
    - name: websocket
      protocol: TCP
      port: 9001
      targetPort: 9001
