apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: k8s-gateway
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://ori-edge.github.io/k8s_gateway/
    chart: k8s-gateway
    targetRevision: 2.4.0
    helm:
      values: |
        domain: kube
        extraZonePlugins:
          - name: log
          - name: errors
          - name: health
            configBlock: |-
              lameduck 5s
          - name: ready
          - name: prometheus
            parameters: 0.0.0.0:9153
          - name: forward
            parameters: . 1.1.1.1 8.8.8.8
          - name: loop
          - name: reload
          - name: loadbalance
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
