apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: traefik-dashboard-homelab
  namespace: traefik
  annotations:
    external-dns.alpha.kubernetes.io/hostname: traefik.home.coolkev.com
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`traefik.home.coolkev.com`) && (PathPrefix(`/dashboard`) || PathPrefix(`/api`))
      kind: Rule
      services:
        - name: api@internal
          kind: TraefikService
  tls:
    certResolver: letsencrypt
