ingressRoute:
  dashboard:
    enabled: true
    entryPoints: ["web"]

ports:
  traefik:
    port: 9000
    expose:
      default: true
    exposedPort: 9000
    protocol: TCP

providers:
  kubernetesIngress:
    publishedService:
      enabled: true
      pathOverride: "traefik/traefik"

certificatesResolvers:
  letsencrypt:
    acme:
      caServer: https://acme-staging-v02.api.letsencrypt.org/directory
      email: kevin@coolkev.com
      storage: /data/acme.json
      dnsChallenge:
        provider: route53
        resolvers:
          - 1.1.1.1:53
          - 8.8.8.8:53
        delayBeforeCheck: 0

tls:
  options:
    default:
      sniStrict: false
  stores:
    default:
      defaultGeneratedCert:
        resolver: letsencrypt

envFrom:
  - secretRef:
      name: traefik-route53-credentials

deployment:
  additionalVolumeMounts:
    - name: acme-storage
      mountPath: /data

  additionalVolumes:
    - name: acme-storage
      nfs:
        server: 10.60.1.15
        path: /data/services/acme

