providers:
  kubernetesIngress:
    publishedService:
      enabled: true
      pathOverride: "traefik/traefik"

# Manage SSL Certificates

certificatesResolvers:
  letsencrypt:
    acme:
      caServer: https://acme-v02.api.letsencrypt.org/directory
      email: kevin@coolkev.com
      storage: /acme/acme.json
      dnsChallenge:
        provider: route53
        resolvers:
          - 1.1.1.1:53
          - 8.8.8.8:53
        delayBeforeCheck: 0

tls:
  options:
    default:
      sniStrict: false
  stores:
    default:
      defaultGeneratedCert:
        resolver: letsencrypt

envFrom:
  - secretRef:
      name: traefik-route53-credentials

additionalVolumeMounts:
  - name: acme-storage
    mountPath: /acme

deployment:
  enabled: true
  additionalVolumes:
    - name: acme-storage
      nfs:
        server: 10.60.1.15
        path: /data/services/acme

# Enable the dashboard
api:
  dashboard: true

ingressRoute:
  dashboard:
    enabled: true
    entryPoints:
      - traefik

ports:
  traefik:
    port: 9000
    expose:
      default: true
    exposedPort: 9000
    protocol: TCP

global:
  sendAnonymousUsage: true
