apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: grafana
  labels:
    app: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:15
          command:
            - "docker-entrypoint.sh"
          args:
            - "postgres"
          env:
            - name: POSTGRES_DB
              value: "grafana"
            - name: POSTGRES_USER
              value: "root"
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: grafana-postgres-secret
                  key: POSTGRES_PASSWORD
            - name: PGDATA
              value: "/var/lib/postgresql/data"
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgres-data
          nfs:
            server: 10.60.1.15
            path: /data/services/grafana-postgres
