apiVersion: v1
kind: Service
metadata:
  name: bastion
  namespace: bastion
  annotations:
    external-dns.alpha.kubernetes.io/hostname: bastion.home.coolkev.com
spec:
  type: LoadBalancer
  ports:
  - port: 22
    targetPort: 22
  selector:
    app: bastion
