apiVersion: v1
kind: Service
metadata:
  name: docker-wyze-bridge
  namespace: home-sensors
spec:
  type: LoadBalancer
  selector:
    app: docker-wyze-bridge
  ports:
    - name: web-ui
      protocol: TCP
      port: 5000
      targetPort: 5000
    - name: web-ui-alt
      protocol: TCP
      port: 5050
      targetPort: 5050
    - name: rtmp
      protocol: TCP
      port: 1935
      targetPort: 1935
    - name: rtsp
      protocol: TCP
      port: 8554
      targetPort: 8554
    - name: hls
      protocol: TCP
      port: 8888
      targetPort: 8888
    - name: webrtc
      protocol: TCP
      port: 8889
      targetPort: 8889
    - name: webrtc-ice
      protocol: UDP
      port: 8189
      targetPort: 8189
