apiVersion: cicd.coolkev.com/v1
kind: DeployConfig
metadata:
  name: weatherflow-tempest-sensor
  namespace: home-sensors
spec:
  resourceType: Deployment
  autodeploy: true
  repo:
    owner: kj800x
    repo: weatherflow-tempest-influxdb-integration
    defaultBranch: master
  spec:
    strategy:
      type: Recreate
    replicas: 1
    revisionHistoryLimit: 1
    selector:
      matchLabels:
        app: weatherflow-tempest-sensor
    template:
      metadata:
        labels:
          app: weatherflow-tempest-sensor
      spec:
        hostNetwork: true
        imagePullSecrets:
          - name: ghcr-kj800x
        containers:
          - name: weatherflow-tempest-sensor
            image: ghcr.io/kj800x/weatherflow-tempest-influxdb-integration
            command: ["/bin/sh", "-c", "node lib/index.js"]
            env:
              - name: NODE_ENV
                value: "production"
              - name: METRICS_PORT
                value: "31036"
            livenessProbe:
              httpGet:
                path: /
                port: 31036
              initialDelaySeconds: 5
              periodSeconds: 10
              timeoutSeconds: 2
              failureThreshold: 3
            workingDir: "/app"
