apiVersion: apps/v1
kind: Deployment
metadata:
  name: weatherflow-tempest-sensor
  namespace: home-sensors
  labels:
    app: weatherflow-tempest-sensor
spec:
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: weatherflow-tempest-sensor
  template:
    metadata:
      labels:
        app: weatherflow-tempest-sensor
    spec:
      imagePullSecrets:
        - name: ghcr-kj800x
      containers:
        - name: weatherflow-tempest-sensor
          image: ghcr.io/kj800x/weatherflow-tempest-influxdb-integration:master
          command: ["/bin/sh", "-c", "node lib/index.js"]
          entrypoint: ["docker-entrypoint.sh"]
          env:
            - name: NODE_ENV
              value: "production"
          ports:
            - containerPort: 50222
              protocol: UDP
            - containerPort: 8080
              protocol: TCP
          workingDir: "/app"
