apiVersion: apps/v1
kind: Deployment
metadata:
  name: weatherflow-tempest-sensor
  namespace: home-sensors
  labels:
    app: weatherflow-tempest-sensor
spec:
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: weatherflow-tempest-sensor
  template:
    metadata:
      labels:
        app: weatherflow-tempest-sensor
    spec:
      hostNetwork: true
      imagePullSecrets:
        - name: ghcr-kj800x
      containers:
        - name: weatherflow-tempest-sensor
          image: ghcr.io/kj800x/weatherflow-tempest-influxdb-integration:sha256-c1c0fc2b42e45f047b28d07359cdeb2f417fbe21ef83cb9e1801feef2a4923c7.sig
          command: ["/bin/sh", "-c", "node lib/index.js"]
          entrypoint: ["docker-entrypoint.sh"]
          env:
            - name: NODE_ENV
              value: "production"
            - name: METRICS_PORT
              value: "31036"
          livenessProbe:
            httpGet:
              path: /
              port: 31036
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 2
            failureThreshold: 3
          workingDir: "/app"
