apiVersion: v1
kind: Service
metadata:
  name: weatherflow-tempest-sensor
  namespace: home-sensors
spec:
  type: LoadBalancer
  selector:
    app: weatherflow-tempest-sensor
  ports:
    - name: weatherflow-udp
      protocol: UDP
      port: 50222
      targetPort: 50222
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
