apiVersion: v1
kind: Service
metadata:
  name: weatherflow-tempest-sensor
  namespace: home-sensors
spec:
  type: LoadBalancer
  selector:
    app: weatherflow-tempest-sensor
  ports:
    - name: http
      protocol: TCP
      port: 9100
      targetPort: 31036
