apiVersion: cicd.coolkev.com/v1
kind: DeployConfig
metadata:
  name: aws-cost-rs
  namespace: home-sensors
spec:
  resourceType: Deployment
  autodeploy: true
  repo:
    owner: kj800x
    repo: aws-cost-rs
    defaultBranch: master
  spec:
    replicas: 1
    revisionHistoryLimit: 1
    selector:
      matchLabels:
        app: aws-cost-rs
    template:
      metadata:
        labels:
          app: aws-cost-rs
      spec:
        imagePullSecrets:
          - name: ghcr-kj800x
        containers:
          - name: aws-cost-rs
            image: ghcr.io/kj800x/aws-cost-rs
            command: ["aws-cost-rs"]
            env:
              - name: AWS_REGION
                value: "us-east-1"
              - name: AWS_ACCESS_KEY_ID
                valueFrom:
                  secretKeyRef:
                    name: aws-cost-credentials
                    key: AWS_ACCESS_KEY_ID
              - name: AWS_SECRET_ACCESS_KEY
                valueFrom:
                  secretKeyRef:
                    name: aws-cost-credentials
                    key: AWS_SECRET_ACCESS_KEY
            ports:
              - containerPort: 9090
                protocol: TCP
            livenessProbe:
              httpGet:
                path: /
                port: 9090
              initialDelaySeconds: 5
              periodSeconds: 10
              timeoutSeconds: 2
              failureThreshold: 3
