apiVersion: apps/v1
kind: Deployment
metadata:
  name: timelapse-rs-grow-tent
  namespace: home-sensors
  labels:
    app: timelapse-rs-grow-tent
spec:
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: timelapse-rs-grow-tent
  template:
    metadata:
      labels:
        app: timelapse-rs-grow-tent
    spec:
      imagePullSecrets:
        - name: ghcr-kj800x
      containers:
        - name: timelapse-rs-grow-tent
          image: kj800x/timelapse-rs:commit-73b539e5dbbbf27d58e729a7e454bd40c4cb4556
          command: ["./timelapse-rs"]
          workingDir: "/usr/src/timelapse-rs"
          env:
            - name: OUTPUT_FOLDER
              value: "/data"
            - name: CAMERA_TYPE
              value: "RTSP"
            - name: SLEEP_SECS
              value: "900"
            - name: FEED_URL
              valueFrom:
                secretKeyRef:
                  name: timelapse-grow-tent-feed-url
                  key: FEED_URL
          ports:
            - containerPort: 9090
          volumeMounts:
            - name: data-volume
              mountPath: /data
          livenessProbe:
            httpGet:
              path: /
              port: 9090
            initialDelaySeconds: 10
            periodSeconds: 30
      volumes:
        - name: data-volume
          nfs:
            server: 10.60.1.15
            path: /data/archive/archive/timelapse/grow-tent
