apiVersion: apps/v1
kind: Deployment
metadata:
  name: cicd
  namespace: argocd
  labels:
    app: cicd
spec:
  revisionHistoryLimit: 1
  replicas: 1
  selector:
    matchLabels:
      app: cicd
  template:
    metadata:
      labels:
        app: cicd
    spec:
      serviceAccountName: cicd-operator
      imagePullSecrets:
        - name: ghcr-kj800x
      containers:
        - name: cicd
          image: ghcr.io/kj800x/cicd:commit-d47acad5ae3411d4b537295dbe05be17d97b19cb
          command: [ "cicd" ]
          env:
            - name: WEBSOCKET_URL
              value: "ws://apps.coolkev.com:8080/ws"
            - name: ENABLE_K8S_CONTROLLER
              value: "true"
            - name: DATABASE_PATH
              value: "/data/db.db"
            - name: CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: cicd-auth
                  key: CLIENT_SECRET
            - name: DISCORD_BOT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: cicd-auth
                  key: DISCORD_BOT_TOKEN
            - name: DISCORD_CHANNEL_ID
              valueFrom:
                secretKeyRef:
                  name: cicd-auth
                  key: DISCORD_CHANNEL_ID
          workingDir: "/usr/src/cicd"
          ports:
            - containerPort: 8080
              protocol: TCP
          volumeMounts:
            - name: cicd-data
              mountPath: /data
      volumes:
        - name: cicd-data
          nfs:
            server: 10.60.1.15
            path: /data/services/cicd
