apiVersion: apps/v1
kind: Deployment
metadata:
  name: cicd
  namespace: cluster-infra
  labels:
    app: cicd
spec:
  revisionHistoryLimit: 1
  replicas: 1
  selector:
    matchLabels:
      app: cicd
  template:
    metadata:
      labels:
        app: cicd
    spec:
      imagePullSecrets:
        - name: ghcr-kj800x
      containers:
        - name: cicd
          image: ghcr.io/kj800x/cicd:commit-221a9c39645a397253fcdb121906fadf139e5f08
          command: [ "cicd" ]
          env:
            - name: WEBSOCKET_URL
              value: "ws://apps.coolkev.com:8080/ws"
            - name: CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: cicd-auth
                  key: CLIENT_SECRET
            - name: DISCORD_BOT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: cicd-auth
                  key: DISCORD_BOT_TOKEN
            - name: DISCORD_CHANNEL_ID
              valueFrom:
                secretKeyRef:
                  name: cicd-auth
                  key: DISCORD_CHANNEL_ID
            - name: ENABLE_K8S_CONTROLLER
              value: "true"
          workingDir: "/usr/src/cicd"
          ports:
            - containerPort: 8080
              protocol: TCP

