apiVersion: cicd.coolkev.com/v1
kind: DeployConfig
metadata:
  name: webhooks-enforcer
  namespace: argocd
spec:
  resourceType: CronJob
  autodeploy: false
  repo:
    owner: kj800x
    repo: webhooks-enforcer
    defaultBranch: master
  spec:
    schedule: "0 * * * *"
    jobTemplate:
      spec:
        template:
          spec:
            restartPolicy: OnFailure
            containers:
              - name: webhooks-enforcer
                image: ghcr.io/kj800x/webhooks-enforcer
                command: ["./webhooks-enforcer"]
                env:
                  - name: GITHUB_PAT
                    valueFrom:
                      secretKeyRef:
                        name: webhooks-enforcer-secret
                        key: GITHUB_PAT
                  - name: WEBHOOK_URL
                    valueFrom:
                      secretKeyRef:
                        name: webhooks-enforcer-secret
                        key: WEBHOOK_URL
                  - name: WEBHOOK_SECRET
                    valueFrom:
                      secretKeyRef:
                        name: webhooks-enforcer-secret
                        key: WEBHOOK_SECRET
                  - name: REPO_OWNER
                    value: "kj800x"
                  - name: DRY_RUN
                    value: "false"
