apiVersion: v1
kind: Service
metadata:
  name: timelapse-service-rs
  namespace: home-sensors
spec:
  type: LoadBalancer
  selector:
    app: timelapse-service-rs
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080
