apiVersion: apps/v1
kind: Deployment
metadata:
  name: victoria-metrics
  namespace: victoria-metrics
  labels:
    app: victoria-metrics
spec:
  strategy:
    # Required because VictoriaMetrics in single-instance mode uses a locking
    # strategy to prevent multiple instances from writing to the same storage
    type: Recreate
  revisionHistoryLimit: 1
  replicas: 1
  selector:
    matchLabels:
      app: victoria-metrics
  template:
    metadata:
      labels:
        app: victoria-metrics
    spec:
      containers:
        - name: victoria-metrics
          image: victoriametrics/victoria-metrics
          command:
            - "/victoria-metrics-prod"
          args:
            - "--promscrape.config=/etc/prometheus/scrape/prometheus.yml"
            - "-maxLabelsPerTimeseries=35"
            - "-selfScrapeInterval=10s"
            - "-retentionPeriod=99y"
          ports:
            - containerPort: 8428
          volumeMounts:
            - name: prometheus-config
              mountPath: /etc/prometheus/scrape
            - name: victoria-metrics-data
              mountPath: /victoria-metrics-data
      volumes:
        - name: prometheus-config
          nfs:
            server: 10.60.1.15
            path: /data/mounts/promscrape/
        - name: victoria-metrics-data
          nfs:
            server: 10.60.1.15
            path: /data/services/victoria-metrics
