apiVersion: v1
kind: Service
metadata:
  name: victoria-metrics-lb
  namespace: victoria-metrics
spec:
  type: LoadBalancer
  selector:
    app: victoria-metrics
  ports:
    - protocol: TCP
      port: 8428
      targetPort: 8428
