apiVersion: v1
kind: Service
metadata:
  name: jellyfin
  namespace: jellyfin
spec:
  type: LoadBalancer
  selector:
    app: jellyfin
  ports:
    - protocol: TCP
      port: 8096
      targetPort: 8096
    - protocol: TCP
      port: 8920
      targetPort: 8920
    - protocol: UDP
      port: 1900
      targetPort: 1900
    - protocol: UDP
      port: 7359
      targetPort: 7359
