apiVersion: v1
kind: Service
metadata:
  name: minecraft-lb
  namespace: minecraft
  annotations:
    external-dns.alpha.kubernetes.io/hostname: minecraft.home.coolkev.com
spec:
  type: LoadBalancer
  selector:
    app: minecraft
  ports:
    - protocol: TCP
      port: 25565
      targetPort: 25565
    - protocol: TCP
      port: 25575
      targetPort: 25575
