apiVersion: v1
kind: Service
metadata:
  name: minecraft-lb
  namespace: minecraft
  annotations:
    external-dns.alpha.kubernetes.io/hostname: minecraft.home.coolkev.com
spec:
  type: NodePort
  selector:
    app: minecraft
  ports:
    - name: minecraft
      protocol: TCP
      port: 25565
      targetPort: 25565
      nodePort: 30565
    - name: rcon
      protocol: TCP
      port: 25575
      targetPort: 25575
      nodePort: 30575
