apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  namespace: argocd
  name: bastion
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: default
  source:
    path: bastion
    repoURL: https://github.com/kj800x/homelab
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
