apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  namespace: argocd
  name: traefik
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: traefik
    server: https://kubernetes.default.svc
  project: default
  sources:
  - repoURL: https://traefik.github.io/charts
    chart: traefik
    targetRevision: 36.3.0
    helm:
      valueFiles:
      - $values/traefik/values.yaml
  - repoURL: https://github.com/kj800x/homelab
    path: traefik
    targetRevision: HEAD
    ref: values
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
