apiVersion: cicd.coolkev.com/v1
kind: DeployConfig
metadata:
  name: tasker
  namespace: tasker
spec:
  resourceType: Deployment
  autodeploy: false
  repo:
    owner: kj800x
    repo: tasker
    defaultBranch: master
  spec:
    revisionHistoryLimit: 1
    replicas: 1
    selector:
      matchLabels:
        app: tasker
    template:
      metadata:
        labels:
          app: tasker
      spec:
        serviceAccountName: tasker-operator
        imagePullSecrets:
          - name: ghcr-kj800x
        containers:
          - name: tasker
            image: ghcr.io/kj800x/tasker
            env:
              - name: NFS_HOST
                value: "10.60.1.15"
              - name: NFS_BASE_DIR
                value: "/data/services/tasker"
              - name: CONTAINER_BASE_DIR
                value: "/tasker-workspace"
              - name: DB_PATH
                value: "/tasker-db/tasker.db"
              - name: KUBERNETES_NAMESPACE
                value: "tasker"
              - name: KUBE_DASHBOARD_URL
                value: "http://k8s.home.coolkev.com/"
            ports:
              - containerPort: 8080
            volumeMounts:
              - name: tasker-workspace-dir
                mountPath: /tasker-workspace
              - name: tasker-db
                mountPath: /tasker-db
        volumes:
          - name: tasker-workspace-dir
            nfs:
              server: 10.60.1.15
              path: /data/services/tasker
          - name: tasker-db
            nfs:
              server: 10.60.1.15
              path: /data/services/tasker-db

