apiVersion: v1
kind: Service
metadata:
  name: tasker
  namespace: tasker
spec:
  type: ClusterIP
  selector:
    app: tasker
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080
